image::https://classroom.github.com/assets/open-in-vscode-2e0aaae1b6195c2367325f4f02e2d04e9abb55f0b24a779b69b11b9e10269abc.svg[link="https://classroom.github.com/online_ide?assignment_repo_id=16926388&assignment_repo_type=AssignmentRepo", alt="Open in Visual Studio Code"]

= SAÉ 3.01 2023-2024
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

**https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/releases/tag/v4.final[version finale]**

toc::[]

== Equipe

Projet est réalisé par::

- https://github.com/LeJoker747[Ethan Besse] Product Owner
- https://github.com/Tarsmio[Tristan Chefaï]
- https://github.com/mtthIA[Matthias Lionardo] Scrum Master
- https://github.com/lohanSR[Lohan Serre]



Tuteur/tutrice enseignant(e) de l'équipe:: mailto:jean-michel.bruel@univ-tlse2.fr[JMB]

== Présentation du client : Rockworld
Rockworld est une entreprise française fondée en 2023 par Thomas Aussenac, Yassine Laghdas, Loïc
Phrakousonh, Joan Casas et Sydney Richards. Elle vend des cailloux connectés, les Rockmon, ils sont éducatifs, interactifs  et personnalisables.
Suite à leur succès rapide, les fondateurs ont vite compris qu'ils auraient besoin d'un site de vente en ligne pour pouvoir vendre les Rockmon plus facilement et avec une interface intuitive pour que les utilisateurs puissent personnaliser et avoir un aperçu de leur compagnon avant achat.

== Contexte général

[[liensUtiles]]
=== Liens utiles

- Le https://webetud.iut-blagnac.fr/course/view.php?id=841[cours Moodle] sur la SAE
- Le dépôt https://github.com/IUT-Blagnac/sae3-01-template[template] qui sert de base à tous les dépôts étudiants.
- Le lien https://classroom.github.com/a/OUF7gxEa[classroom] si besoin.
- Consultez ce https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/T%C3%A9l%C3%A9travail/teletravail.adoc[document] pour connaître les membres de l'équipe actuellement en télétravail.


== Réalisations  

https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Doc%20Technique.adoc[Doc Technique] + 
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Doc%20Utilisateur.adoc[Doc Utilisateur] + 
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Doc-Conception.adoc[Document de Conception] +
https://github.com/orgs/IUT-Blagnac/projects/271/views/8[Backlog Produit] +
http://193.54.227.208/~R2024SAE3006/[Lien vers le site E-Commerce de Rockworld] +
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Cahier_Recette_Site.adoc[Cahier de recette] + 
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/FicheConseilsJuridiques.pdf[Fiche de conseils juridiques et de sécurité]


== Communication EP

=== retour semaine 48 
Pas d'ODJ , pas de CR !
note : 0/3

=== retour semaine 49
ODJ : Ok mais manque Ecommerce !  CR: pb de date (22/11) au lieu de 4/12. Manque abs/Présent.  Manque analyse difficultés/Réussites, manque futur resp de la reunion semaine 50. Manque Point client Web (d'ailleurs peu d'infos sur la partie web).
note : 1,83/3
Note appel offre : 10/20

=== retour semaine 50
odj OK; CR : Il manque le retour reunion client et analyse réussites/difficultés (techniques et organisationnelles). Peu d'avancement sur le site ce qui vous pénalise sur la note GPO, c'est dommage.  Je n'ai pas vu les jours de télétravail attention aux UAS en fin de projet.
NOTE : 2,24/3

=== retour semaine 51
Pensez à indiquer la salle de réunion, l'IUT est grand. CR:analyse réussites difficultés à développer. Pensez à m'envoyer l'ODJ pour la semaine prochaine
2,5/3
semaine 48 corrigée mais avec pénalité de retard (-1 point) : 0,81/3

== Gestion de projet & Qualité

[cols="1,3"]
|===
| Sprints | Documents 

| Sprint#1 |https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Doc%20Technique.adoc[Doc Technique] + 
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Doc%20Utilisateur.adoc[Doc Utilisateur] + 
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Doc-Conception.adoc[Document de Conception] +
https://github.com/orgs/IUT-Blagnac/projects/271/views/7[Backlog Sprint#1] +
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Ordre%20du%20jour%20n%C2%B01.pdf[Ordre du jour] +
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Compte%20rendu%20n%C2%B01.pdf[Compte rendu]
| Sprint #2 |https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Ordre%20du%20jour%20n%C2%B02.pdf[Ordre du jour] +
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/CompteRendu_n%C2%B02.pdf[Compte Rendu] +
https://github.com/orgs/IUT-Blagnac/projects/271/views/10?filterQuery=iteration%3A%22Sprint+%232%22[Backlog Sprint#2]
| Sprint #3 |https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/ODJ_n%C2%B03.pdf[Ordre du jour] +
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/CompteRenduN%C2%B03.pdf[Compte Rendu] + 
https://github.com/orgs/IUT-Blagnac/projects/271/views/14[Backlog sprint #3] +
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Cahier_Recette_Site.adoc[Cahier de recette]
| Sprint #4 |https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Ordre%20du%20jour%20n%C2%B04.pdf[Ordre du jour] +
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Compte%20rendu%20n%C2%B04.pdf[Compte Rendu] + 
https://github.com/orgs/IUT-Blagnac/projects/271/views/16?groupedBy%5BcolumnId%5D=&sliceBy%5Bvalue%5D=Sprint+%234[Backlog sprint #4] +
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Cahier_Recette_Site.adoc[Cahier de recette]
| Sprint #5 |https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Cahier_Recette_Site.adoc[Cahier de recette] +
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Documentation%20utilisateur.pdf[Documentation utilisateur] +
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/Doc-Conception.adoc[Doc-Conception] +
http://193.54.227.208/~R2024SAE3006/[Site final Rockworld]
|===


https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a8/blob/master/Documentation/ODJ%20r%C3%A9union%20post-mortem.pdf[Ordre du jour réunion post-mortem]

=== Evaluation bi-hebdomadaire

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=881427875&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=881427875&amp;format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=881427875&amp;format=interactive"></iframe>
++++
endif::[]
=== retour sprint 1 / Initialisation du dépôt

Penser à mettre les rôles dans le readme. A présenter le client. On peut aller un peu plus loin que le titre pour les docs. Il manque la doc de conception qui devrait être bien démarrée. Le lien Backlog renvoi vers le backlog sprint 1 ce n'est pas la même chose. Je dois avoir le backlog produit complet ! Attention les issues/ Task doivent toutes êtres ratachées à une US (ex. Créer les footer).  Elles doivent être assignées. Pas de cahier de tests, heureusement quelques critères d'acceptabilité dans les pauvres US que vous avez recensées.Pas de release ni de date de release. Il reste du travail !!

=== retour semaine 48

Backlog produit : je n'ai pas de lien vers le backlog produit; Des US sans finalité (afin de) et sans critères d'acceptabilité, manque compléxité. Backlog sprint : Je n'en ai pas ... Les US traitées dans un sprint devraient au moins avoir un milestone à jour (sprint 1 par ex). Je n'ai que le spint 1 qui devrait être fini depuis un moment, ou est le sprint 2 ?Tasks : Elles doivent être rattachées à des US, assignées, avec un milestone. Il y en a peu ... impossible de suivre où vous en êtes du projet ! TESTS : pas de cahier de tests DOC: liens mais peu d'éléments notamment dans la doc de conception qui devrait être terminée !! release : Pas de release, pas de site en construction visible, pas de dates de livrable.

=== retour semaine 50
Des progrès , le sprint 3 se rapproche des attendus mais les tâches doivent être rattachées aux US. Après j'ai très peu de US et d'issue, il manque la plupart des tâches techniques.  Toujours pas de cahier de tests !  Doc tech et user juste initialisée et conception au même stade que la dernière fois !  Site web en demo ok , j'ai une release IOT mais pas Web.
Pensez à raffraichir la page pour voir le graphique des évaluations.

=== retour semaine 2
Il manque encore le afin de dans les US du sprint et tâches non rattachées.  Documentations : enfin !  Pensez à rappeler le contexte !  Peu de fonctionnalités admin développées. Pour la doc de conception il fallait la faire évoluer en doc technique pour permettre la maintenance du site. cahier de recette ok dommage qu'il n'a pas été fait avant.
note provisoire : 10,9/20
Note fiche de droit : 14/20
