= Cahier de Recette
:toc-title: Table des matières
:toc: macro

*Par :* _BESSE Ethan, CHEFAI Tristan, LIONARDO Matthias, SERRE Lohan_ +
*Pour :* _RockWorld_ +
*Équipe : 2A8* 

---
toc::[]
---
== Introduction

== I. 

=== I.1. Création d'un nouveau compte (SERRE Lohan)
- **Description :** Tester la fonctionnalité de création de compte.
- **Cas de test :**

|====
|Titre 4+|Créer un compte utilisateur
|Objectif 4+|Vérifier qu'un nouvel utilisateur peut s'inscrire avec succès.
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|1 ^|Accéder à la page d'inscription. ^|La page du formulaire d'inscription s'affiche correctement. ^|Aucune ^|OK
^|2 ^|Remplir le formulaire d'inscription avec des informations valides et cliquer sur "S'inscrire". ^|Le compte est créé et l'utilisateur est redirigé vers la page de connexion^|Les informations sont valides ^|OK
^|3 ^|Remplir le formulaire d'inscription avec des informations non valides et cliquer sur "S'inscrire". ^|Une erreur s'affiche^|Les informations ne sont pas valides ^|OK
^|4 ^|Remplir le formulaire d'inscription avec une adresse mail déjà existante. ^|Une erreur s'affiche et la création de compte s'annule^|L'adresse mail est associé à un autre compte ^|OK
5+|
5+|Commentaire :
Ce cas de test valide la procédure complète de création de compte d'un nouvel utilisateur.
|====

=== I.2. Détails d'un produit (SERRE Lohan)
- **Description :** Tester la consultation des détails d'un produit.
- **Cas de test :**

|====
|Titre 4+|Visualiser les détails d'un produit
|Objectif 4+|Vérifier que les informations de la page correspondent au produit sélectionné.
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|1 ^|Accéder à la page des informations des produits. ^|Les informations du produit (Nom, Description, Fil d'ariane, Stock, Prix, Avis) sont présentes et correctes ^|Le produit possède les informations principales ^|OK
^|2 ^|Affichage de la photo du produit ^|La photo du produit est affichée et correspond au produit ^|Le produit possède une photo associée ^|OK
^|3 ^|Affichage de la rupture de stock d'un produit ^|"Rupture de stock" est affiché en rouge ^|Le produit est en rupture de stock ^|OK

5+|
5+|Commentaire :
Ce cas de test valide l'affichage des informations d'un produit
|====

=== I.3. Barre de recherche (SERRE Lohan)
- **Description :** Tester la recherche d'un produit avec la barre de recherche
- **Cas de test :**

|====
|Titre 4+|Rechercher un produit
|Objectif 4+|Vérifier qu'un utilisateur peut rechercher un produit 
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|1 ^|Entrer un mot-clé correspondant au produit qu'on veut rechercher ^|Les produits correspondants s'affichent avec les filtres ^|Des produits existent correspondant aux mot-clés saisis ^|OK
5+|
5+|Commentaire :
Ce cas de test valide la recherche d'un produit
|====

=== I.4. Avis (SERRE Lohan)
- **Description :** Tester l'ajout et l'affichage des avis
- **Cas de test :**

|====
|Titre 4+|Ajout et affichage des avis
|Objectif 4+|Vérifier qu'un utilisateur peut voir et ajouter des avis 
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|1 ^|Cliquer sur le bouton "Donner votre avis" ^|Un formulaire s'affiche pour permettre d'ajouter un avis ^|L'utilisateur a acheté le produit. ^|OK
^|2 ^|Valider l'avis ^|La page du produit se recharge et l'avis de l'utilisateur est présent dans la section "Avis Clients" ^|L'utilisateur a entré des informations valides pour ajouter un avis ^|OK
^|3 ^|Aucune ^|Les avis de tous les utilisateurs sont affichés dans la section "Avis Clients" ^|Le produit possède des avis ^|OK
5+|
5+|Commentaire :
Ce cas de test valide l'ajout et l'affichage des avis
|====


=== I.5. Affichage du catalogue produit (LIONARDO Matthias)
- **Description :** Tester L'affichage du catalogue produit
- **Cas de test :**

|====
|Titre 4+|Afficher catalogue produit
|Objectif 4+|Vérifier que les produits de la catégorie soient présents
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|1 ^|Cliquer sur une catégorie du menu  ^|Tous les produits de la catégorie s'affichent ^|Il y a des produits dans la catégorie. ^|OK
^|2 ^|Cliquer sur une catégorie du menu ^|Un message s'affiche pour prévenir qu'il n'y a aucun produit dans la catégorie ^|Il n'y a aucun produits dans la catégorie. ^|OK
^|3 ^|Tentative de modification du lien ^|Tous les produits s'affichent ^|L'utilisateur modifie le lien ^|OK
5+|
5+|Commentaire :
Ce cas de test valide l'affichage du catalogue produit
|====

=== I.6. Ajouter produit (LIONARDO Matthias)
- **Description :** Tester L'ajout d'un produit
- **Cas de test :**

|====
|Titre 4+|Ajouter un produit
|Objectif 4+|Vérifier que le produit est bien ajouté
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|1 ^|Cliquer sur le bouton ajouter produit  ^|Un message s'affiche pour prévenir que le produit a été ajouté ^|Être connecté sur un compte administrateur/ remplir tous les champs. ^|OK
5+|
5+|Commentaire :
Ce cas de test valide l'ajout d'un produit
|====

=== I.7. Supprimer produit (LIONARDO Matthias)
- **Description :** Tester La suppression d'un produit
- **Cas de test :**

|====
|Titre 4+|Supprimer produit
|Objectif 4+|Vérifier que le produit soit bien supprimé
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|1 ^|Appuyer sur le bouton supprimer  ^|Supprime le produit ^|Être connecté sur un compte administrateur. ^|OK
^|2 ^|Appuyer sur le bouton supprimer  ^|Supprime le produit ^|Être connecté sur un compte administrateur/ Le produit est dans une commande ou le panier d'un utilisateur. ^|Le produit n'est pas supprimé. ^|
5+|
5+|Commentaire :
Ce cas de test valide la suppression d'un produit
|====

=== I.8. Modifier produit (LIONARDO Matthias)
- **Description :** Tester La modification d'un produit
- **Cas de test :**

|====
|Titre 4+|Modifier produit
|Objectif 4+|Vérifier que le produit soit bien modifié
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|1 ^|Cliquer sur le bouton modifier  ^|Modifie le produit ^|Être connecté sur un compte administrateur. ^|OK
5+|
5+|Commentaire :
Ce cas de test valide la modification d'un produit
|====

=== I.9. Ajouter Categorie (LIONARDO Matthias)
- **Description :** Tester L'ajout d'une catégorie
- **Cas de test :**

|====
|Titre 4+|Ajouter Catégorie
|Objectif 4+|Vérifier que la catégorie est bien ajoutée
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|1 ^|Cliquer le bouton "Ajouter"  ^|Ajoute la catégorie et affiche un message ^|Être connecté sur un compte administrateur. ^|OK
5+|
5+|Commentaire :
Ce cas de test valide l'ajout d'une catégorie
|====

=== I.10. Supprimer Categorie (LIONARDO Matthias)
- **Description :** Tester la suppression d'une catégorie
- **Cas de test :**

|====
|Titre 4+|Supprimer une catégorie
|Objectif 4+|Vérifier qu'une catégorie peut être supprimée
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|1 ^|Cliquer sur le bouton "Supprimer" d'une catégorie  ^|La catégorie est supprimée ^|Être connecté sur un compte administrateur. ^|OK
^|2 ^|Cliquer sur le bouton "Supprimer" d'une catégorie  ^|Un message d'erreur s'affiche ^|Être connecté sur un compte administrateur/ La categorie a des sous categories. ^|OK
^|3 ^|Cliquer sur le bouton "Supprimer" d'une catégorie  ^|Un message d'erreur s'affiche ^|Être connecté sur un compte administrateur/ La categorie a des produits. ^|OK
5+|
5+|Commentaire :
Ce cas de test valide la suppression d'une catégorie
|====


=== I.11. Modifier Compte Client (LIONARDO Matthias)
- **Description :** Tester la modification d'un compte client
- **Cas de test :**

|====
|Titre 4+|Modifier Compte Client
|Objectif 4+|Vérifier que le compte client est bien modifié
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|1 ^|Cliquer sur le bouton "Modifier" ^|Le compte est modifié ^|Être connecté en tant qu'utilisateur ^|OK
^|2 ^|Cliquer sur le bouton "Modifier" ^|Le compte n'est pas modifié et les champs posant problème sont mis en rouge ^|Être connecté en tant qu'utilisateur/ L'adresse e-mail existe déja ou les champs renseignés ne sont pas valide ^|OK
5+|
5+|Commentaire :
Ce cas de test valide la modification d'un compte client
|====

=== I.12. Afficher Commande Compte Client (LIONARDO Matthias)
- **Description :** Tester l'affichage d'un compte client
- **Cas de test :**

|====
|Titre 4+|Afficher Compte Client
|Objectif 4+|Vérifier que le compte client s'affiche correctement
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|1 ^|Aucune ^|Les produits favoris s'affichent ^|Être connecté en tant qu'utilisateur/ avoir des produits favoris ^|OK
^|2 ^|Aucune ^|un message "Aucun produit favoris" s'affiche ^|Être connecté en tant qu'utilisateur/ n'avoir aucun produit en favoris ^|OK
^|3 ^|Aucune ^|Les produits commandé s'affichent ^|Être connecté en tant qu'utilisateur/ avoir des produits commandés ^|OK
^|4 ^|Aucune ^|un message "Aucun produit commandés" s'affiche ^|Être connecté en tant qu'utilisateur/ n'avoir aucun produit commandés ^|OK
5+|
5+|Commentaire :
Ce cas de test valide l'affichage d'un compte client
|====


